import pandas as pd
from pathlib import Path

def get_project_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent

def load_results() -> pd.DataFrame:
    """Loads the international football results dataset."""
    root = get_project_root()
    path1 = root / "data" / "raw" / "results.csv"
    path2 = root / "dataset" / "results.csv"
    
    if path1.exists():
        path = path1
    elif path2.exists():
        path = path2
    else:
        raise FileNotFoundError(f"Dataset not found at {path1} or {path2}. Please place results.csv there.")
    
    df = pd.read_csv(path)
    df['date'] = pd.to_datetime(df['date'])
    return df

def load_players() -> pd.DataFrame:
    """Loads the Transfermarkt players dataset.

    Searches in multiple locations:
      1. data/raw/players.csv  (generated by scripts/generate_sample_players.py)
      2. dataset/players.csv   (if downloaded from Kaggle directly)
    """
    root = get_project_root()
    path1 = root / "data" / "raw" / "players.csv"
    path2 = root / "dataset" / "players.csv"

    if path1.exists():
        path = path1
    elif path2.exists():
        path = path2
    else:
        raise FileNotFoundError(
            f"Players dataset not found at {path1} or {path2}. "
            "Please run: python scripts/generate_sample_players.py"
        )

    df = pd.read_csv(path)
    # Ensure date_of_birth is parsed if present
    if 'date_of_birth' in df.columns:
        df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], errors='coerce')
    return df

def load_sentiment() -> pd.DataFrame:
    """Loads the sentiment dataset (Phase 3).

    Searches in multiple locations:
      1. data/raw/sentiment.csv  (generated by scripts/generate_sample_sentiment.py)
      2. dataset/sentiment.csv   (alternative location)
    """
    root = get_project_root()
    path1 = root / "data" / "raw" / "sentiment.csv"
    path2 = root / "dataset" / "sentiment.csv"

    if path1.exists():
        path = path1
    elif path2.exists():
        path = path2
    else:
        raise FileNotFoundError(
            f"Sentiment dataset not found at {path1} or {path2}. "
            "Please run: python scripts/generate_sample_sentiment.py"
        )

    df = pd.read_csv(path)
    df['date'] = pd.to_datetime(df['date'])
    return df
